# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

CMAKE_FLAGS := -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE)
DOC_DOWNLOAD_URL_BASE := https://raw.githubusercontent.com/neovim/doc/gh-pages
CLINT_ERRORS_FILE_PATH := /reports/clint/errors.json
>>>>>>> upstream/master

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/George/Documents/Programs/C/neovim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/George/Documents/Programs/C/neovim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

<<<<<<< HEAD
# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast
=======
testlint: | nvim
	$(BUILD_CMD) -C build testlint

test: functionaltest
>>>>>>> upstream/master

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/George/Documents/Programs/C/neovim/CMakeFiles /Users/George/Documents/Programs/C/neovim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/George/Documents/Programs/C/neovim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark-prereqs

# Build rule for target.
benchmark-prereqs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark-prereqs
.PHONY : benchmark-prereqs

# fast build rule for target.
benchmark-prereqs/fast:
	$(MAKE) -f CMakeFiles/benchmark-prereqs.dir/build.make CMakeFiles/benchmark-prereqs.dir/build
.PHONY : benchmark-prereqs/fast

#=============================================================================
# Target rules for targets named functionaltest

# Build rule for target.
functionaltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functionaltest
.PHONY : functionaltest

# fast build rule for target.
functionaltest/fast:
	$(MAKE) -f CMakeFiles/functionaltest.dir/build.make CMakeFiles/functionaltest.dir/build
.PHONY : functionaltest/fast

#=============================================================================
# Target rules for targets named functionaltest-prereqs

# Build rule for target.
functionaltest-prereqs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functionaltest-prereqs
.PHONY : functionaltest-prereqs

# fast build rule for target.
functionaltest-prereqs/fast:
	$(MAKE) -f CMakeFiles/functionaltest-prereqs.dir/build.make CMakeFiles/functionaltest-prereqs.dir/build
.PHONY : functionaltest-prereqs/fast

#=============================================================================
# Target rules for targets named unittest

# Build rule for target.
unittest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest
.PHONY : unittest

# fast build rule for target.
unittest/fast:
	$(MAKE) -f CMakeFiles/unittest.dir/build.make CMakeFiles/unittest.dir/build
.PHONY : unittest/fast

#=============================================================================
# Target rules for targets named unittest-prereqs

# Build rule for target.
unittest-prereqs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest-prereqs
.PHONY : unittest-prereqs

# fast build rule for target.
unittest-prereqs/fast:
	$(MAKE) -f CMakeFiles/unittest-prereqs.dir/build.make CMakeFiles/unittest-prereqs.dir/build
.PHONY : unittest-prereqs/fast

#=============================================================================
# Target rules for targets named libnvim

# Build rule for target.
libnvim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libnvim
.PHONY : libnvim

# fast build rule for target.
libnvim/fast:
	$(MAKE) -f src/nvim/CMakeFiles/libnvim.dir/build.make src/nvim/CMakeFiles/libnvim.dir/build
.PHONY : libnvim/fast

#=============================================================================
# Target rules for targets named nvim

# Build rule for target.
nvim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nvim
.PHONY : nvim

# fast build rule for target.
nvim/fast:
	$(MAKE) -f src/nvim/CMakeFiles/nvim.dir/build.make src/nvim/CMakeFiles/nvim.dir/build
.PHONY : nvim/fast

#=============================================================================
# Target rules for targets named nvim-test

# Build rule for target.
nvim-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nvim-test
.PHONY : nvim-test

# fast build rule for target.
nvim-test/fast:
	$(MAKE) -f src/nvim/CMakeFiles/nvim-test.dir/build.make src/nvim/CMakeFiles/nvim-test.dir/build
.PHONY : nvim-test/fast

#=============================================================================
# Target rules for targets named check-po-af

# Build rule for target.
check-po-af: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-af
.PHONY : check-po-af

# fast build rule for target.
check-po-af/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-af.dir/build.make src/nvim/po/CMakeFiles/check-po-af.dir/build
.PHONY : check-po-af/fast

#=============================================================================
# Target rules for targets named check-po-ca

# Build rule for target.
check-po-ca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ca
.PHONY : check-po-ca

# fast build rule for target.
check-po-ca/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ca.dir/build.make src/nvim/po/CMakeFiles/check-po-ca.dir/build
.PHONY : check-po-ca/fast

#=============================================================================
# Target rules for targets named check-po-cs

# Build rule for target.
check-po-cs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-cs
.PHONY : check-po-cs

# fast build rule for target.
check-po-cs/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-cs.dir/build.make src/nvim/po/CMakeFiles/check-po-cs.dir/build
.PHONY : check-po-cs/fast

#=============================================================================
# Target rules for targets named check-po-cs.cp1250

# Build rule for target.
check-po-cs.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-cs.cp1250
.PHONY : check-po-cs.cp1250

# fast build rule for target.
check-po-cs.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-cs.cp1250.dir/build.make src/nvim/po/CMakeFiles/check-po-cs.cp1250.dir/build
.PHONY : check-po-cs.cp1250/fast

#=============================================================================
# Target rules for targets named check-po-de

# Build rule for target.
check-po-de: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-de
.PHONY : check-po-de

# fast build rule for target.
check-po-de/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-de.dir/build.make src/nvim/po/CMakeFiles/check-po-de.dir/build
.PHONY : check-po-de/fast

#=============================================================================
# Target rules for targets named check-po-en_GB

# Build rule for target.
check-po-en_GB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-en_GB
.PHONY : check-po-en_GB

# fast build rule for target.
check-po-en_GB/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-en_GB.dir/build.make src/nvim/po/CMakeFiles/check-po-en_GB.dir/build
.PHONY : check-po-en_GB/fast

#=============================================================================
# Target rules for targets named check-po-eo

# Build rule for target.
check-po-eo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-eo
.PHONY : check-po-eo

# fast build rule for target.
check-po-eo/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-eo.dir/build.make src/nvim/po/CMakeFiles/check-po-eo.dir/build
.PHONY : check-po-eo/fast

#=============================================================================
# Target rules for targets named check-po-es

# Build rule for target.
check-po-es: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-es
.PHONY : check-po-es

# fast build rule for target.
check-po-es/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-es.dir/build.make src/nvim/po/CMakeFiles/check-po-es.dir/build
.PHONY : check-po-es/fast

#=============================================================================
# Target rules for targets named check-po-fi

# Build rule for target.
check-po-fi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-fi
.PHONY : check-po-fi

# fast build rule for target.
check-po-fi/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-fi.dir/build.make src/nvim/po/CMakeFiles/check-po-fi.dir/build
.PHONY : check-po-fi/fast

#=============================================================================
# Target rules for targets named check-po-fr

# Build rule for target.
check-po-fr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-fr
.PHONY : check-po-fr

# fast build rule for target.
check-po-fr/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-fr.dir/build.make src/nvim/po/CMakeFiles/check-po-fr.dir/build
.PHONY : check-po-fr/fast

#=============================================================================
# Target rules for targets named check-po-ga

# Build rule for target.
check-po-ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ga
.PHONY : check-po-ga

# fast build rule for target.
check-po-ga/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ga.dir/build.make src/nvim/po/CMakeFiles/check-po-ga.dir/build
.PHONY : check-po-ga/fast

#=============================================================================
# Target rules for targets named check-po-it

# Build rule for target.
check-po-it: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-it
.PHONY : check-po-it

# fast build rule for target.
check-po-it/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-it.dir/build.make src/nvim/po/CMakeFiles/check-po-it.dir/build
.PHONY : check-po-it/fast

#=============================================================================
# Target rules for targets named check-po-ja

# Build rule for target.
check-po-ja: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ja
.PHONY : check-po-ja

# fast build rule for target.
check-po-ja/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ja.dir/build.make src/nvim/po/CMakeFiles/check-po-ja.dir/build
.PHONY : check-po-ja/fast

#=============================================================================
# Target rules for targets named check-po-ja.euc-jp

# Build rule for target.
check-po-ja.euc-jp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ja.euc-jp
.PHONY : check-po-ja.euc-jp

# fast build rule for target.
check-po-ja.euc-jp/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ja.euc-jp.dir/build.make src/nvim/po/CMakeFiles/check-po-ja.euc-jp.dir/build
.PHONY : check-po-ja.euc-jp/fast

#=============================================================================
# Target rules for targets named check-po-ja.sjis

# Build rule for target.
check-po-ja.sjis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ja.sjis
.PHONY : check-po-ja.sjis

# fast build rule for target.
check-po-ja.sjis/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ja.sjis.dir/build.make src/nvim/po/CMakeFiles/check-po-ja.sjis.dir/build
.PHONY : check-po-ja.sjis/fast

#=============================================================================
# Target rules for targets named check-po-ko

# Build rule for target.
check-po-ko: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ko
.PHONY : check-po-ko

# fast build rule for target.
check-po-ko/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ko.dir/build.make src/nvim/po/CMakeFiles/check-po-ko.dir/build
.PHONY : check-po-ko/fast

#=============================================================================
# Target rules for targets named check-po-ko.UTF-8

# Build rule for target.
check-po-ko.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ko.UTF-8
.PHONY : check-po-ko.UTF-8

# fast build rule for target.
check-po-ko.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ko.UTF-8.dir/build.make src/nvim/po/CMakeFiles/check-po-ko.UTF-8.dir/build
.PHONY : check-po-ko.UTF-8/fast

#=============================================================================
# Target rules for targets named check-po-nb

# Build rule for target.
check-po-nb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-nb
.PHONY : check-po-nb

# fast build rule for target.
check-po-nb/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-nb.dir/build.make src/nvim/po/CMakeFiles/check-po-nb.dir/build
.PHONY : check-po-nb/fast

#=============================================================================
# Target rules for targets named check-po-nl

# Build rule for target.
check-po-nl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-nl
.PHONY : check-po-nl

# fast build rule for target.
check-po-nl/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-nl.dir/build.make src/nvim/po/CMakeFiles/check-po-nl.dir/build
.PHONY : check-po-nl/fast

#=============================================================================
# Target rules for targets named check-po-no

# Build rule for target.
check-po-no: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-no
.PHONY : check-po-no

# fast build rule for target.
check-po-no/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-no.dir/build.make src/nvim/po/CMakeFiles/check-po-no.dir/build
.PHONY : check-po-no/fast

#=============================================================================
# Target rules for targets named check-po-pl

# Build rule for target.
check-po-pl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-pl
.PHONY : check-po-pl

# fast build rule for target.
check-po-pl/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-pl.dir/build.make src/nvim/po/CMakeFiles/check-po-pl.dir/build
.PHONY : check-po-pl/fast

#=============================================================================
# Target rules for targets named check-po-pl.UTF-8

# Build rule for target.
check-po-pl.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-pl.UTF-8
.PHONY : check-po-pl.UTF-8

# fast build rule for target.
check-po-pl.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-pl.UTF-8.dir/build.make src/nvim/po/CMakeFiles/check-po-pl.UTF-8.dir/build
.PHONY : check-po-pl.UTF-8/fast

#=============================================================================
# Target rules for targets named check-po-pl.cp1250

# Build rule for target.
check-po-pl.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-pl.cp1250
.PHONY : check-po-pl.cp1250

# fast build rule for target.
check-po-pl.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-pl.cp1250.dir/build.make src/nvim/po/CMakeFiles/check-po-pl.cp1250.dir/build
.PHONY : check-po-pl.cp1250/fast

#=============================================================================
# Target rules for targets named check-po-pt_BR

# Build rule for target.
check-po-pt_BR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-pt_BR
.PHONY : check-po-pt_BR

# fast build rule for target.
check-po-pt_BR/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-pt_BR.dir/build.make src/nvim/po/CMakeFiles/check-po-pt_BR.dir/build
.PHONY : check-po-pt_BR/fast

#=============================================================================
# Target rules for targets named check-po-ru

# Build rule for target.
check-po-ru: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ru
.PHONY : check-po-ru

# fast build rule for target.
check-po-ru/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ru.dir/build.make src/nvim/po/CMakeFiles/check-po-ru.dir/build
.PHONY : check-po-ru/fast

#=============================================================================
# Target rules for targets named check-po-ru.cp1251

# Build rule for target.
check-po-ru.cp1251: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-ru.cp1251
.PHONY : check-po-ru.cp1251

# fast build rule for target.
check-po-ru.cp1251/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-ru.cp1251.dir/build.make src/nvim/po/CMakeFiles/check-po-ru.cp1251.dir/build
.PHONY : check-po-ru.cp1251/fast

#=============================================================================
# Target rules for targets named check-po-sk

# Build rule for target.
check-po-sk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-sk
.PHONY : check-po-sk

# fast build rule for target.
check-po-sk/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-sk.dir/build.make src/nvim/po/CMakeFiles/check-po-sk.dir/build
.PHONY : check-po-sk/fast

#=============================================================================
# Target rules for targets named check-po-sk.cp1250

# Build rule for target.
check-po-sk.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-sk.cp1250
.PHONY : check-po-sk.cp1250

# fast build rule for target.
check-po-sk.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-sk.cp1250.dir/build.make src/nvim/po/CMakeFiles/check-po-sk.cp1250.dir/build
.PHONY : check-po-sk.cp1250/fast

#=============================================================================
# Target rules for targets named check-po-sv

# Build rule for target.
check-po-sv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-sv
.PHONY : check-po-sv

# fast build rule for target.
check-po-sv/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-sv.dir/build.make src/nvim/po/CMakeFiles/check-po-sv.dir/build
.PHONY : check-po-sv/fast

#=============================================================================
# Target rules for targets named check-po-uk

# Build rule for target.
check-po-uk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-uk
.PHONY : check-po-uk

# fast build rule for target.
check-po-uk/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-uk.dir/build.make src/nvim/po/CMakeFiles/check-po-uk.dir/build
.PHONY : check-po-uk/fast

#=============================================================================
# Target rules for targets named check-po-uk.cp1251

# Build rule for target.
check-po-uk.cp1251: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-uk.cp1251
.PHONY : check-po-uk.cp1251

# fast build rule for target.
check-po-uk.cp1251/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-uk.cp1251.dir/build.make src/nvim/po/CMakeFiles/check-po-uk.cp1251.dir/build
.PHONY : check-po-uk.cp1251/fast

#=============================================================================
# Target rules for targets named check-po-vi

# Build rule for target.
check-po-vi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-vi
.PHONY : check-po-vi

# fast build rule for target.
check-po-vi/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-vi.dir/build.make src/nvim/po/CMakeFiles/check-po-vi.dir/build
.PHONY : check-po-vi/fast

#=============================================================================
# Target rules for targets named check-po-zh_CN

# Build rule for target.
check-po-zh_CN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-zh_CN
.PHONY : check-po-zh_CN

# fast build rule for target.
check-po-zh_CN/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-zh_CN.dir/build.make src/nvim/po/CMakeFiles/check-po-zh_CN.dir/build
.PHONY : check-po-zh_CN/fast

#=============================================================================
# Target rules for targets named check-po-zh_CN.UTF-8

# Build rule for target.
check-po-zh_CN.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-zh_CN.UTF-8
.PHONY : check-po-zh_CN.UTF-8

# fast build rule for target.
check-po-zh_CN.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-zh_CN.UTF-8.dir/build.make src/nvim/po/CMakeFiles/check-po-zh_CN.UTF-8.dir/build
.PHONY : check-po-zh_CN.UTF-8/fast

#=============================================================================
# Target rules for targets named check-po-zh_CN.cp936

# Build rule for target.
check-po-zh_CN.cp936: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-zh_CN.cp936
.PHONY : check-po-zh_CN.cp936

# fast build rule for target.
check-po-zh_CN.cp936/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-zh_CN.cp936.dir/build.make src/nvim/po/CMakeFiles/check-po-zh_CN.cp936.dir/build
.PHONY : check-po-zh_CN.cp936/fast

#=============================================================================
# Target rules for targets named check-po-zh_TW

# Build rule for target.
check-po-zh_TW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-zh_TW
.PHONY : check-po-zh_TW

# fast build rule for target.
check-po-zh_TW/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-zh_TW.dir/build.make src/nvim/po/CMakeFiles/check-po-zh_TW.dir/build
.PHONY : check-po-zh_TW/fast

#=============================================================================
# Target rules for targets named check-po-zh_TW.UTF-8

# Build rule for target.
check-po-zh_TW.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check-po-zh_TW.UTF-8
.PHONY : check-po-zh_TW.UTF-8

# fast build rule for target.
check-po-zh_TW.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/check-po-zh_TW.UTF-8.dir/build.make src/nvim/po/CMakeFiles/check-po-zh_TW.UTF-8.dir/build
.PHONY : check-po-zh_TW.UTF-8/fast

#=============================================================================
# Target rules for targets named potfile

# Build rule for target.
potfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 potfile
.PHONY : potfile

# fast build rule for target.
potfile/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/potfile.dir/build.make src/nvim/po/CMakeFiles/potfile.dir/build
.PHONY : potfile/fast

#=============================================================================
# Target rules for targets named sjiscorr

# Build rule for target.
sjiscorr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sjiscorr
.PHONY : sjiscorr

# fast build rule for target.
sjiscorr/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/sjiscorr.dir/build.make src/nvim/po/CMakeFiles/sjiscorr.dir/build
.PHONY : sjiscorr/fast

#=============================================================================
# Target rules for targets named translations

# Build rule for target.
translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 translations
.PHONY : translations

# fast build rule for target.
translations/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/translations.dir/build.make src/nvim/po/CMakeFiles/translations.dir/build
.PHONY : translations/fast

#=============================================================================
# Target rules for targets named update-po

# Build rule for target.
update-po: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po
.PHONY : update-po

# fast build rule for target.
update-po/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po.dir/build.make src/nvim/po/CMakeFiles/update-po.dir/build
.PHONY : update-po/fast

#=============================================================================
# Target rules for targets named update-po-af

# Build rule for target.
update-po-af: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-af
.PHONY : update-po-af

# fast build rule for target.
update-po-af/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-af.dir/build.make src/nvim/po/CMakeFiles/update-po-af.dir/build
.PHONY : update-po-af/fast

#=============================================================================
# Target rules for targets named update-po-ca

# Build rule for target.
update-po-ca: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ca
.PHONY : update-po-ca

# fast build rule for target.
update-po-ca/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ca.dir/build.make src/nvim/po/CMakeFiles/update-po-ca.dir/build
.PHONY : update-po-ca/fast

#=============================================================================
# Target rules for targets named update-po-cs

# Build rule for target.
update-po-cs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-cs
.PHONY : update-po-cs

# fast build rule for target.
update-po-cs/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-cs.dir/build.make src/nvim/po/CMakeFiles/update-po-cs.dir/build
.PHONY : update-po-cs/fast

#=============================================================================
# Target rules for targets named update-po-cs.cp1250

# Build rule for target.
update-po-cs.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-cs.cp1250
.PHONY : update-po-cs.cp1250

# fast build rule for target.
update-po-cs.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-cs.cp1250.dir/build.make src/nvim/po/CMakeFiles/update-po-cs.cp1250.dir/build
.PHONY : update-po-cs.cp1250/fast

#=============================================================================
# Target rules for targets named update-po-de

# Build rule for target.
update-po-de: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-de
.PHONY : update-po-de

# fast build rule for target.
update-po-de/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-de.dir/build.make src/nvim/po/CMakeFiles/update-po-de.dir/build
.PHONY : update-po-de/fast

#=============================================================================
# Target rules for targets named update-po-en_GB

# Build rule for target.
update-po-en_GB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-en_GB
.PHONY : update-po-en_GB

# fast build rule for target.
update-po-en_GB/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-en_GB.dir/build.make src/nvim/po/CMakeFiles/update-po-en_GB.dir/build
.PHONY : update-po-en_GB/fast

#=============================================================================
# Target rules for targets named update-po-eo

# Build rule for target.
update-po-eo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-eo
.PHONY : update-po-eo

# fast build rule for target.
update-po-eo/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-eo.dir/build.make src/nvim/po/CMakeFiles/update-po-eo.dir/build
.PHONY : update-po-eo/fast

#=============================================================================
# Target rules for targets named update-po-es

# Build rule for target.
update-po-es: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-es
.PHONY : update-po-es

# fast build rule for target.
update-po-es/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-es.dir/build.make src/nvim/po/CMakeFiles/update-po-es.dir/build
.PHONY : update-po-es/fast

#=============================================================================
# Target rules for targets named update-po-fi

# Build rule for target.
update-po-fi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-fi
.PHONY : update-po-fi

# fast build rule for target.
update-po-fi/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-fi.dir/build.make src/nvim/po/CMakeFiles/update-po-fi.dir/build
.PHONY : update-po-fi/fast

#=============================================================================
# Target rules for targets named update-po-fr

# Build rule for target.
update-po-fr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-fr
.PHONY : update-po-fr

# fast build rule for target.
update-po-fr/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-fr.dir/build.make src/nvim/po/CMakeFiles/update-po-fr.dir/build
.PHONY : update-po-fr/fast

#=============================================================================
# Target rules for targets named update-po-ga

# Build rule for target.
update-po-ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ga
.PHONY : update-po-ga

# fast build rule for target.
update-po-ga/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ga.dir/build.make src/nvim/po/CMakeFiles/update-po-ga.dir/build
.PHONY : update-po-ga/fast

#=============================================================================
# Target rules for targets named update-po-it

# Build rule for target.
update-po-it: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-it
.PHONY : update-po-it

# fast build rule for target.
update-po-it/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-it.dir/build.make src/nvim/po/CMakeFiles/update-po-it.dir/build
.PHONY : update-po-it/fast

#=============================================================================
# Target rules for targets named update-po-ja

# Build rule for target.
update-po-ja: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ja
.PHONY : update-po-ja

# fast build rule for target.
update-po-ja/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ja.dir/build.make src/nvim/po/CMakeFiles/update-po-ja.dir/build
.PHONY : update-po-ja/fast

#=============================================================================
# Target rules for targets named update-po-ja.euc-jp

# Build rule for target.
update-po-ja.euc-jp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ja.euc-jp
.PHONY : update-po-ja.euc-jp

# fast build rule for target.
update-po-ja.euc-jp/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ja.euc-jp.dir/build.make src/nvim/po/CMakeFiles/update-po-ja.euc-jp.dir/build
.PHONY : update-po-ja.euc-jp/fast

#=============================================================================
# Target rules for targets named update-po-ja.sjis

# Build rule for target.
update-po-ja.sjis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ja.sjis
.PHONY : update-po-ja.sjis

# fast build rule for target.
update-po-ja.sjis/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ja.sjis.dir/build.make src/nvim/po/CMakeFiles/update-po-ja.sjis.dir/build
.PHONY : update-po-ja.sjis/fast

#=============================================================================
# Target rules for targets named update-po-ko

# Build rule for target.
update-po-ko: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ko
.PHONY : update-po-ko

# fast build rule for target.
update-po-ko/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ko.dir/build.make src/nvim/po/CMakeFiles/update-po-ko.dir/build
.PHONY : update-po-ko/fast

#=============================================================================
# Target rules for targets named update-po-ko.UTF-8

# Build rule for target.
update-po-ko.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ko.UTF-8
.PHONY : update-po-ko.UTF-8

# fast build rule for target.
update-po-ko.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ko.UTF-8.dir/build.make src/nvim/po/CMakeFiles/update-po-ko.UTF-8.dir/build
.PHONY : update-po-ko.UTF-8/fast

#=============================================================================
# Target rules for targets named update-po-nb

# Build rule for target.
update-po-nb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-nb
.PHONY : update-po-nb

# fast build rule for target.
update-po-nb/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-nb.dir/build.make src/nvim/po/CMakeFiles/update-po-nb.dir/build
.PHONY : update-po-nb/fast

#=============================================================================
# Target rules for targets named update-po-nl

# Build rule for target.
update-po-nl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-nl
.PHONY : update-po-nl

# fast build rule for target.
update-po-nl/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-nl.dir/build.make src/nvim/po/CMakeFiles/update-po-nl.dir/build
.PHONY : update-po-nl/fast

#=============================================================================
# Target rules for targets named update-po-no

# Build rule for target.
update-po-no: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-no
.PHONY : update-po-no

# fast build rule for target.
update-po-no/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-no.dir/build.make src/nvim/po/CMakeFiles/update-po-no.dir/build
.PHONY : update-po-no/fast

#=============================================================================
# Target rules for targets named update-po-pl

# Build rule for target.
update-po-pl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-pl
.PHONY : update-po-pl

# fast build rule for target.
update-po-pl/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-pl.dir/build.make src/nvim/po/CMakeFiles/update-po-pl.dir/build
.PHONY : update-po-pl/fast

#=============================================================================
# Target rules for targets named update-po-pl.UTF-8

# Build rule for target.
update-po-pl.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-pl.UTF-8
.PHONY : update-po-pl.UTF-8

# fast build rule for target.
update-po-pl.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-pl.UTF-8.dir/build.make src/nvim/po/CMakeFiles/update-po-pl.UTF-8.dir/build
.PHONY : update-po-pl.UTF-8/fast

#=============================================================================
# Target rules for targets named update-po-pl.cp1250

# Build rule for target.
update-po-pl.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-pl.cp1250
.PHONY : update-po-pl.cp1250

# fast build rule for target.
update-po-pl.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-pl.cp1250.dir/build.make src/nvim/po/CMakeFiles/update-po-pl.cp1250.dir/build
.PHONY : update-po-pl.cp1250/fast

#=============================================================================
# Target rules for targets named update-po-pt_BR

# Build rule for target.
update-po-pt_BR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-pt_BR
.PHONY : update-po-pt_BR

# fast build rule for target.
update-po-pt_BR/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-pt_BR.dir/build.make src/nvim/po/CMakeFiles/update-po-pt_BR.dir/build
.PHONY : update-po-pt_BR/fast

#=============================================================================
# Target rules for targets named update-po-ru

# Build rule for target.
update-po-ru: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ru
.PHONY : update-po-ru

# fast build rule for target.
update-po-ru/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ru.dir/build.make src/nvim/po/CMakeFiles/update-po-ru.dir/build
.PHONY : update-po-ru/fast

#=============================================================================
# Target rules for targets named update-po-ru.cp1251

# Build rule for target.
update-po-ru.cp1251: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-ru.cp1251
.PHONY : update-po-ru.cp1251

# fast build rule for target.
update-po-ru.cp1251/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-ru.cp1251.dir/build.make src/nvim/po/CMakeFiles/update-po-ru.cp1251.dir/build
.PHONY : update-po-ru.cp1251/fast

#=============================================================================
# Target rules for targets named update-po-sk

# Build rule for target.
update-po-sk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-sk
.PHONY : update-po-sk

# fast build rule for target.
update-po-sk/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-sk.dir/build.make src/nvim/po/CMakeFiles/update-po-sk.dir/build
.PHONY : update-po-sk/fast

#=============================================================================
# Target rules for targets named update-po-sk.cp1250

# Build rule for target.
update-po-sk.cp1250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-sk.cp1250
.PHONY : update-po-sk.cp1250

# fast build rule for target.
update-po-sk.cp1250/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-sk.cp1250.dir/build.make src/nvim/po/CMakeFiles/update-po-sk.cp1250.dir/build
.PHONY : update-po-sk.cp1250/fast

#=============================================================================
# Target rules for targets named update-po-sv

# Build rule for target.
update-po-sv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-sv
.PHONY : update-po-sv

# fast build rule for target.
update-po-sv/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-sv.dir/build.make src/nvim/po/CMakeFiles/update-po-sv.dir/build
.PHONY : update-po-sv/fast

#=============================================================================
# Target rules for targets named update-po-uk

# Build rule for target.
update-po-uk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-uk
.PHONY : update-po-uk

# fast build rule for target.
update-po-uk/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-uk.dir/build.make src/nvim/po/CMakeFiles/update-po-uk.dir/build
.PHONY : update-po-uk/fast

#=============================================================================
# Target rules for targets named update-po-uk.cp1251

# Build rule for target.
update-po-uk.cp1251: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-uk.cp1251
.PHONY : update-po-uk.cp1251

# fast build rule for target.
update-po-uk.cp1251/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-uk.cp1251.dir/build.make src/nvim/po/CMakeFiles/update-po-uk.cp1251.dir/build
.PHONY : update-po-uk.cp1251/fast

#=============================================================================
# Target rules for targets named update-po-vi

# Build rule for target.
update-po-vi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-vi
.PHONY : update-po-vi

# fast build rule for target.
update-po-vi/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-vi.dir/build.make src/nvim/po/CMakeFiles/update-po-vi.dir/build
.PHONY : update-po-vi/fast

#=============================================================================
# Target rules for targets named update-po-zh_CN

# Build rule for target.
update-po-zh_CN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-zh_CN
.PHONY : update-po-zh_CN

# fast build rule for target.
update-po-zh_CN/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-zh_CN.dir/build.make src/nvim/po/CMakeFiles/update-po-zh_CN.dir/build
.PHONY : update-po-zh_CN/fast

#=============================================================================
# Target rules for targets named update-po-zh_CN.UTF-8

# Build rule for target.
update-po-zh_CN.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-zh_CN.UTF-8
.PHONY : update-po-zh_CN.UTF-8

# fast build rule for target.
update-po-zh_CN.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-zh_CN.UTF-8.dir/build.make src/nvim/po/CMakeFiles/update-po-zh_CN.UTF-8.dir/build
.PHONY : update-po-zh_CN.UTF-8/fast

#=============================================================================
# Target rules for targets named update-po-zh_CN.cp936

# Build rule for target.
update-po-zh_CN.cp936: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-zh_CN.cp936
.PHONY : update-po-zh_CN.cp936

# fast build rule for target.
update-po-zh_CN.cp936/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-zh_CN.cp936.dir/build.make src/nvim/po/CMakeFiles/update-po-zh_CN.cp936.dir/build
.PHONY : update-po-zh_CN.cp936/fast

#=============================================================================
# Target rules for targets named update-po-zh_TW

# Build rule for target.
update-po-zh_TW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-zh_TW
.PHONY : update-po-zh_TW

# fast build rule for target.
update-po-zh_TW/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-zh_TW.dir/build.make src/nvim/po/CMakeFiles/update-po-zh_TW.dir/build
.PHONY : update-po-zh_TW/fast

#=============================================================================
# Target rules for targets named update-po-zh_TW.UTF-8

# Build rule for target.
update-po-zh_TW.UTF-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update-po-zh_TW.UTF-8
.PHONY : update-po-zh_TW.UTF-8

# fast build rule for target.
update-po-zh_TW.UTF-8/fast:
	$(MAKE) -f src/nvim/po/CMakeFiles/update-po-zh_TW.UTF-8.dir/build.make src/nvim/po/CMakeFiles/update-po-zh_TW.UTF-8.dir/build
.PHONY : update-po-zh_TW.UTF-8/fast

#=============================================================================
# Target rules for targets named unittest-headers

# Build rule for target.
unittest-headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittest-headers
.PHONY : unittest-headers

# fast build rule for target.
unittest-headers/fast:
	$(MAKE) -f test/includes/CMakeFiles/unittest-headers.dir/build.make test/includes/CMakeFiles/unittest-headers.dir/build
.PHONY : unittest-headers/fast

#=============================================================================
# Target rules for targets named shell-test

# Build rule for target.
shell-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shell-test
.PHONY : shell-test

# fast build rule for target.
shell-test/fast:
	$(MAKE) -f test/functional/fixtures/CMakeFiles/shell-test.dir/build.make test/functional/fixtures/CMakeFiles/shell-test.dir/build
.PHONY : shell-test/fast

#=============================================================================
# Target rules for targets named tty-test

# Build rule for target.
tty-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tty-test
.PHONY : tty-test

# fast build rule for target.
tty-test/fast:
	$(MAKE) -f test/functional/fixtures/CMakeFiles/tty-test.dir/build.make test/functional/fixtures/CMakeFiles/tty-test.dir/build
.PHONY : tty-test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... unittest-prereqs"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... functionaltest"
	@echo "... install"
	@echo "... functionaltest-prereqs"
	@echo "... benchmark"
	@echo "... list_install_components"
	@echo "... benchmark-prereqs"
	@echo "... unittest"
	@echo "... install/local"
	@echo "... nvim-test"
	@echo "... nvim"
	@echo "... libnvim"
	@echo "... check-po-pt_BR"
	@echo "... check-po-es"
	@echo "... check-po-zh_CN.UTF-8"
	@echo "... check-po-fr"
	@echo "... update-po-ja.euc-jp"
	@echo "... check-po-ja"
	@echo "... update-po-zh_CN.cp936"
	@echo "... update-po-zh_TW"
	@echo "... check-po-zh_TW"
	@echo "... check-po-it"
	@echo "... check-po-zh_TW.UTF-8"
	@echo "... check-po-ko"
	@echo "... update-po-zh_CN.UTF-8"
	@echo "... check-po-nb"
	@echo "... check-po-nl"
	@echo "... update-po-af"
	@echo "... check-po-ja.sjis"
	@echo "... check-po-no"
	@echo "... update-po-ca"
	@echo "... check-po-pl.cp1250"
	@echo "... update-po-zh_TW.UTF-8"
	@echo "... check-po-pl"
	@echo "... check-po-cs.cp1250"
	@echo "... check-po-uk.cp1251"
	@echo "... potfile"
	@echo "... update-po-de"
	@echo "... check-po-ru.cp1251"
	@echo "... update-po-cs"
	@echo "... check-po-sk"
	@echo "... update-po-ga"
	@echo "... check-po-sk.cp1250"
	@echo "... update-po-fi"
	@echo "... sjiscorr"
	@echo "... check-po-ru"
	@echo "... update-po-eo"
	@echo "... update-po"
	@echo "... update-po-es"
	@echo "... check-po-uk"
	@echo "... check-po-sv"
	@echo "... check-po-vi"
	@echo "... update-po-fr"
	@echo "... update-po-ja"
	@echo "... update-po-it"
	@echo "... update-po-ko"
	@echo "... update-po-nb"
	@echo "... update-po-pl.cp1250"
	@echo "... update-po-en_GB"
	@echo "... check-po-en_GB"
	@echo "... update-po-cs.cp1250"
	@echo "... update-po-uk.cp1251"
	@echo "... update-po-nl"
	@echo "... update-po-no"
	@echo "... update-po-ru.cp1251"
	@echo "... update-po-zh_CN"
	@echo "... check-po-zh_CN"
	@echo "... update-po-sk.cp1250"
	@echo "... update-po-pl"
	@echo "... update-po-sk"
	@echo "... update-po-ru"
	@echo "... update-po-uk"
	@echo "... check-po-ja.euc-jp"
	@echo "... update-po-sv"
	@echo "... update-po-vi"
	@echo "... update-po-ja.sjis"
	@echo "... check-po-af"
	@echo "... check-po-ko.UTF-8"
	@echo "... check-po-ca"
	@echo "... update-po-ko.UTF-8"
	@echo "... translations"
	@echo "... check-po-de"
	@echo "... check-po-pl.UTF-8"
	@echo "... check-po-cs"
	@echo "... check-po-zh_CN.cp936"
	@echo "... check-po-ga"
	@echo "... check-po-fi"
	@echo "... update-po-pt_BR"
	@echo "... check-po-eo"
	@echo "... update-po-pl.UTF-8"
	@echo "... unittest-headers"
	@echo "... shell-test"
	@echo "... tty-test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

lint:
	cmake -DLINT_PRG=./clint.py \
		-DLINT_DIR=src \
		-DLINT_SUPPRESS_URL="$(DOC_DOWNLOAD_URL_BASE)$(CLINT_ERRORS_FILE_PATH)" \
		-P cmake/RunLint.cmake

.PHONY: test testlint functionaltest unittest lint clean distclean nvim libnvim cmake deps install
